version: '3.8'
services:
  statserver:
    build: stat/server
    image: stat_server_image
    container_name: stat_server_container
    ports:
      - "9090:9090"
    depends_on:
      - statdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  statdb:
    image: postgres:13.7-alpine
    container_name: statdb
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - DB_HOST=statdb
      - DB_PORT=5432
