DROP TABLE IF EXISTS users, categories, locations, events, requests, compilations, events_compilations;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
	CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
	CONSTRAINT uc_categories_name UNIQUE (name)
);

CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat real NOT NULL,
	lon real NOT NULL
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id bigint NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    location_id bigint NOT NULL,
    paid boolean NOT NULL,
    participant_limit bigint NOT NULL,
    request_moderation boolean NOT NULL,
    state VARCHAR NOT NULL,
    title VARCHAR(120) NOT NULL,
    initiator_id bigint NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
	CONSTRAINT fk_categories_category_id FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE CASCADE,
	CONSTRAINT fk_locations_location_id FOREIGN KEY(location_id) REFERENCES locations (id) ON DELETE CASCADE,
	CONSTRAINT fk_users_user_id FOREIGN KEY(initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    status VARCHAR,
	CONSTRAINT fk_events_event_id FOREIGN KEY(event_id) REFERENCES events (id) ON DELETE CASCADE,
	CONSTRAINT fk_users_requester_id FOREIGN KEY(requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE events_compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint,
    compilation_id bigint,
    CONSTRAINT fk_events_compilations_event_id FOREIGN KEY(event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilations_compilations_event_id FOREIGN KEY(compilation_id)
    REFERENCES compilations (id) ON DELETE CASCADE
);
